### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by enderahmetyurt** [ergenekonyigit/ktu-ieee-cs-ruby#1]
Merhaba,
Kodlar çok güzel ancak neyin ne iş yaptığını, sorunun ne olduğu README'ye yazarsanız bence daha güzel olabilir. Yani kod hangi sorunu çözüyor gibi.
Sevgiler.

**Comment by ergenekonyigit** [comment]
Tesekkurler, en yakin zamanda readmeye hangi odevde neler istendigini ekleyecegim. 👍
